import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { groq } from '@/lib/groq/client'
import type { ChatMessage } from '@/types'
import type { GroqModelId } from '@/lib/groq/models'
import { renderToBuffer } from '@react-pdf/renderer'
import { createElement } from 'react'
import { MaidReportDoc } from '@/components/report/MaidReportDoc'

export const runtime = 'nodejs'
export const maxDuration = 120

export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { sessionId, title, history, modelId = 'llama-3.3-70b-versatile' } = await req.json() as {
      sessionId?: string
      title: string
      history: ChatMessage[]
      modelId?: GroqModelId
    }

    // ── 1. Generate the full report text via Groq ───────────────────────────
    const conversationSummary = history
      .slice(-30)
      .map(m => `${m.role === 'user' ? 'Researcher' : 'MAID'}: ${m.content}`)
      .join('\n\n')

    const reportPrompt = `You are MAID — a professional medical AI research assistant. Based on the following research conversation, generate a comprehensive, professional research report of approximately 25-30 pages (8000-10000 words).

RESEARCH CONVERSATION:
${conversationSummary}

Generate a complete professional report with ALL of the following sections:

# ${title}

## Executive Summary
[500 word summary of key findings]

## 1. Introduction & Background
[Comprehensive background, 600+ words]

## 2. Pharmacological Profile
[Detailed pharmacology including mechanism of action, receptor binding, pharmacodynamics — 800+ words]

## 3. Pharmacokinetics (ADMET)
[Full ADMET analysis with tables for absorption, distribution, metabolism, excretion, toxicity — 700+ words]

## 4. Molecular Properties & Drug-Likeness
[Lipinski Ro5, Veber rules, TPSA, molecular weight analysis with data table — 600+ words]

## 5. Clinical Evidence & Efficacy
[Clinical trial data, efficacy endpoints, outcome data — 800+ words]

## 6. Safety Profile & Adverse Events
[Comprehensive adverse events table, contraindications, warnings — 700+ words]

## 7. Drug Interactions
[Known interactions table with severity ratings — 600+ words]

## 8. Therapeutic Applications
[Current indications and emerging applications — 500+ words]

## 9. Comparative Analysis
[Comparison table with related drugs/compounds — 600+ words]

## 10. Regulatory Status
[FDA/EMA approval status, indications — 400+ words]

## 11. Future Research Directions
[Ongoing trials, research gaps, potential — 500+ words]

## 12. Conclusion
[Comprehensive conclusion — 400+ words]

## References & Data Sources
[List all databases used: PubChem, ChEMBL, OpenFDA, ClinicalTrials.gov, UniProt, RxNorm]

---
IMPORTANT: 
- Use extensive markdown tables for data
- Be scientifically rigorous and cite data sources
- Include specific numbers, percentages, and values where available
- This is a professional pharmaceutical research report
- End with: "⚠️ This report is generated by AI for research purposes only. All findings must be verified by qualified professionals before clinical application."`

    const response = await groq.chat.completions.create({
      model: modelId,
      messages: [{ role: 'user', content: reportPrompt }],
      temperature: 0.3,
      max_tokens: 8000,
    })

    const reportContent = response.choices[0].message.content ?? 'Report generation failed.'

    // ── 2. Save report to DB ────────────────────────────────────────────────
    const reportRecord = {
      user_id: user.id,
      session_id: sessionId ?? null,
      title,
      content: reportContent,
      created_at: new Date().toISOString(),
    }

    const { data: savedReport } = await supabase
      .from('research_reports')
      .insert(reportRecord)
      .select()
      .single()

    // ── 3. Generate PDF buffer ──────────────────────────────────────────────
    const pdfBuffer = await renderToBuffer(
      createElement(MaidReportDoc, {
        title,
        content: reportContent,
        generatedAt: new Date().toISOString(),
        author: user.email ?? 'Researcher',
      })
    )

    // ── 4. Return PDF as download ───────────────────────────────────────────
    const filename = `MAID_Report_${title.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 50)}_${Date.now()}.pdf`

    // Convert Node.js Buffer → Uint8Array so NextResponse accepts it
    const uint8 = new Uint8Array(pdfBuffer)

    return new NextResponse(uint8, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'X-Report-Id': savedReport?.id ?? '',
        'X-Report-Title': encodeURIComponent(title),
      },
    })
  } catch (e) {
    console.error('Report generation error:', e)
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }
}
